global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nestjs'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
